## Visualizacion

#### se realizara una visualizacion de los datos, a la vez un etl para una mejor lectura de los mismos a posterior.

importaciones

In [27]:
import pandas as pd
import numpy as np
from datetime import datetime

In [28]:
# como primer paso realizare una visualizacion de los datos y una comprension de los mismos.
homicidios_hechos = pd.read_excel('datasets/homicidios.xlsx', sheet_name='HECHOS')
homicidios_hechos.head(5)

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS

### Explicacion de cada columna del excel Echos.

#### Nombres de columnas y sus valores

| Columna                | Definiciones                                                                               |
|------------------------|--------------------------------------------------------------------------------------------|
| ID                     | Identificador único del siniestro                                                         |
| N_VICTIMAS             | Cantidad de víctimas                                                                       |
| FECHA                  | Fecha en formato dd/mm/aaaa                                                                |
| AAAA                   | Año                                                                                        |
| MM                     | Mes                                                                                        |
| DD                     | Día del mes                                                                                |
| HORA                   | Hora del siniestro                                                                         |
| HH                     | Franja horaria entera                                                                      |
| LUGAR_DEL_HECHO        | Dirección del hecho                                                                        |
| TIPO_DE_CALLE          | Tipo de arteria. En el caso de intersecciones a nivel se clasifica según la de mayor jerarquía |
| Calle                  | Nombre de la arteria donde se produjo el hecho                                             |
| Altura                 | Altura de la arteria donde se produjo el hecho                                              |
| Cruce                  | Cruce en caso de que sea una encrucijada                                                    |
| Dirección Normalizada  | Dirección en formato normalizado USIG                                                       |
| COMUNA                 | Comuna de la ciudad (1 a 15)                                                               |
| XY (CABA)              | Geocodificación plana                                                                      |
| pos x                  | Longitud con separador punto. WGS84                                                         |
| pos y                  | Latitud con separador punto. WGS84                                                          |
| PARTICIPANTES          | Conjunción de víctima y acusado                                                             |
| VICTIMA/Vehículo       | Quien ocupaba el vehículo que haya fallecido o se haya lastimado a raíz del hecho, o bien peatón/a. Clasificación agregada del tipo de vehículos |
| ACUSADO/Vehículo       | Quien ocupaba el vehículo que resultó acusado/a del hecho, sin implicar culpabilidad legal |

### Empezamos con la correccion de datos para poder realizar un EDA mas comodo

In [29]:
homicidios_hechos.rename(columns={'ID': 'Id',
                                  'N_VICTIMAS':'Cantidad_Victimas',
                                  'FECHA':'Fecha',
                                  'AAAA':'Anio',
                                  'MM':'Mes',
                                  'DD':'Dia',
                                  'HORA':'Hora',
                                  'HH':'Franja_Horaria',
                                  'LUGAR_DEL_HECHO':'Lugar_Hecho',
                                  'TIPO_DE_CALLE':'Tipo_Calle',
                                  'COMUNA':'Barrio',
                                  'pos x':'Coordenada x',
                                  'pos y':'Coordenada y',
                                  'PARTICIPANTES':'Participantes',
                                  'VICTIMA':'Victima',
                                  'ACUSADO':'Acusado'}, inplace=True)
homicidios_hechos

,Id,Cantidad_Victimas,Fecha,Anio,Mes,Dia,Hora,Franja_Horaria,Lugar_Hecho,Tipo_Calle,...,Altura,Cruce,Dirección Normalizada,Barrio,XY (CABA),Coordenada x,Coordenada y,Participantes,Victima,Acusado
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [30]:
# vemos cantidad de nulos y tipos de datos en cada columna.
homicidios_hechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id                     696 non-null    object
 1   Cantidad_Victimas      696 non-null    int64
 2   Fecha                  696 non-null    datetime64[ns]
 3   Anio                   696 non-null    int64
 4   Mes                    696 non-null    int64
 5   Dia                    696 non-null    int64
 6   Hora                   696 non-null    object
 7   Franja_Horaria         696 non-null    object
 8   Lugar_Hecho            696 non-null    object
 9   Tipo_Calle             696 non-null    object
 10  Calle                  695 non-null    object
 11  Altura                 129 non-null    float64
 12  Cruce                  525 non-null    object
 13  Dirección Normalizada  688 non-null    object
 14  Barrio                 696 non-null    int64
 15  XY (CABA)              696 non-null    object
 16  Coordenada x           696 non-null    object
 17  Coordenada y           696 non-null    object
 18  Participantes          696 non-null    object
 19  Victima                696 non-null    object
 20  Acusado                696 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(14)
memory usage: 114.3+ KB

In [31]:
homicidios_hechos.isnull().sum()

Id                         0
Cantidad_Victimas          0
Fecha                      0
Anio                       0
Mes                        0
Dia                        0
Hora                       0
Franja_Horaria             0
Lugar_Hecho                0
Tipo_Calle                 0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
Barrio                     0
XY (CABA)                  0
Coordenada x               0
Coordenada y               0
Participantes              0
Victima                    0
Acusado                    0
dtype: int64

#### Cambios en los datos de cada columna

| Columna              | Cambio                                                                                         |
|----------------------|------------------------------------------------------------------------------------------------|
| Id                   | Se eliminará el elemento "-" para convertir la columna en tipo entero (integer)               |
| Fecha                | Se eliminará el horario del formato, mostrando solo la fecha                                  |
| Hora                 | Se encontraron unos pocos valores atipicos como ej:"1900-01-02T00:00:00.000" por lo que se procedera a corregirlos    |
| Franja_Horaria       | Se cambiará a un formato:                                                                          |
|                      | - Mañana (6:01 a 12:00)                                                                         |
|                      | - Tarde (12:01 a 19:00)                                                                         |
|                      | - Noche (19:01 a 24:00)                                                                         |
|                      | - Madrugada (24:01 a 6:00)                                                                      |
| Calle                | Se encontró un valor nulo en la columna, por lo que se cambiará a "SD" (Sin Dato)            |
| Altura               | Se cambiarán los valores faltantes por "cruce_de_calles", ya que se encontró una correlación entre la columna "Altura" y "Cruce". Si existe dato en una columna, falta en la otra. |                         
| Cruce                | Se cambiarán los datos:                                                                          |
|                      | - Cuando sea un cruce, por "si"                                                                |
|                      | - Cuando sea faltante, por "no"                                                                |
| Direccion Normalizada| Se eliminará la columna, ya que hay otra columna que proporciona los mismos datos              |
| XY (CABA)            | Se eliminará la columna, ya que hay otras dos columnas que proporcionan los mismos datos     |

In [32]:
############  Procedemos a realizar los cambios propuestos ############ 

# cambio columna ID
homicidios_hechos['Id'] = homicidios_hechos['Id'].str.replace('-', '')
homicidios_hechos['Id'] = homicidios_hechos['Id'].astype(int) 

# cambios columna Fecha
homicidios_hechos['Fecha'] = homicidios_hechos['Fecha'].dt.strftime('%Y-%m-%d')

# cambios en la columna Hora
def convertir_a_time(x):
    '''
    Convierte un valor a un objeto de tiempo (time) de Python si es posible.

    Esta función acepta diferentes tipos de entrada y trata de convertirlos en objetos de tiempo (time) de Python.
    Si la conversión no es posible, devuelve None.

    Parameters:
        x (str, datetime, or any): El valor que se desea convertir a un objeto de tiempo (time).

    Returns:
        datetime.time or None: Un objeto de tiempo (time) de Python si la conversión es exitosa,
        o None si no es posible realizar la conversión.
    '''
    if isinstance(x, str):
        try:
            return datetime.strptime(x, "%H:%M:%S").time()
        except ValueError:
            return None
    elif isinstance(x, datetime):
        return x.time()
    return x

# Se cambia el tipo de dato
homicidios_hechos['Hora'] = homicidios_hechos['Hora'].apply(lambda x: convertir_a_time(x))

# se observa en la fila 518 que quedo un valor faltante por lo que se asignara el valor 00:00:00 para no tener faltantes.
homicidios_hechos["Hora"].fillna("00:00:00", inplace=True)

#cambios en la columna Franja Horaria
def convertir_franja_horaria(valor):
  if isinstance(valor, int):
    if valor > 6 and valor <= 12:
      return "Mañana"
    elif valor > 12 and valor <= 19:
      return "Tarde"
    elif valor > 19 and valor <= 24:
      return "Noche"
    else:
      return "Madrugada"
  else:
    return valor

# Aplica la función a la columna "Franja_Horaria"
homicidios_hechos["Franja_Horaria"] = homicidios_hechos["Franja_Horaria"].apply(convertir_franja_horaria)

# cambios en la columna Calle
homicidios_hechos["Calle"].fillna("SD", inplace=True)

# cambios en la columna Altura
homicidios_hechos["Altura"].fillna("cruce_de_calles", inplace=True)

# cambios en la columna Cruce
def convertir_columna_Cruce(valor):
  if isinstance(valor, str):
    return "si"
  else:
    return "no"

# Aplica la función a la columna
homicidios_hechos ["Cruce"] = homicidios_hechos["Cruce"].apply(convertir_columna_Cruce)

# cambios en las columnas Dirección Normalizada y XY (CABA)
# al final decidi eliminar la columna cruce ya que los datos ya quedarian integrados en la columna altura
homicidios_hechos = homicidios_hechos.drop(columns=["Dirección Normalizada", "XY (CABA)", "Cruce"])

#################################################################################
""" 
LOS SIGUIENTES CAMBIOS NO FUERON AGREGADOS A LA LISTA DE MODIFICACIONES 
YA QUE ERAN PRINCIPALMENTE PARA LA VISUALIZACION DEL DASHBOARD EN POWER BI.
"""
#################################################################################

# agrego una columna para la visualizacion posterior en el dashboard

# Convertir la hora a string para asegurarse de que todos los valores sean de tipo string
homicidios_hechos['Hora'] = homicidios_hechos['Hora'].astype(str)

# Extraer la hora del día de la columna 'Hora'
homicidios_hechos['Hora del día'] = pd.to_datetime(homicidios_hechos['Hora']).dt.hour

# Contar la cantidad de homicidios por hora del día
conteo_por_hora = homicidios_hechos['Hora del día'].value_counts().sort_index()

###################################################################################

# Crear una nueva columna para almacenar la conversión de la columna 'Fecha' a datetime
homicidios_hechos['Fecha_Convertida'] = pd.to_datetime(homicidios_hechos['Fecha'])

# Obtener el nombre del día de la semana
homicidios_hechos['Dia_Semana'] = homicidios_hechos['Fecha_Convertida'].dt.day_name()

# Definir el tipo de día basado en el día de la semana
homicidios_hechos['Tipo_Dia'] = homicidios_hechos['Dia_Semana'].apply(lambda x: 'Dia_de_Semana' if x in ['Thursday', 'Friday', 'Monday', 'Tuesday', 'Wednesday'] else 'Fin_de_Semana')

# Reordenar el DataFrame según el orden de los días de la semana
dias_semana_ordenados = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
homicidios_hechos = homicidios_hechos.sort_values('Fecha_Convertida')
homicidios_hechos['Dia_Semana'] = pd.Categorical(homicidios_hechos['Dia_Semana'], categories=dias_semana_ordenados, ordered=True)

# se elimina la columna copiada
homicidios_hechos = homicidios_hechos.drop(columns=["Fecha_Convertida"])

# Mostrar el DataFrame
homicidios_hechos

C:\Users\junio\AppData\Local\Temp\ipykernel_20616\3427926263.py:61: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'cruce_de_calles' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  homicidios_hechos["Altura"].fillna("cruce_de_calles", inplace=True)
C:\Users\junio\AppData\Local\Temp\ipykernel_20616\3427926263.py:90: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  homicidios_hechos['Hora del día'] = pd.to_datetime(homicidios_hechos['Hora']).dt.hour

,Id,Cantidad_Victimas,Fecha,Anio,Mes,Dia,Hora,Franja_Horaria,Lugar_Hecho,Tipo_Calle,...,Altura,Barrio,Coordenada x,Coordenada y,Participantes,Victima,Acusado,Hora del día,Dia_Semana,Tipo_Dia
0,20160001,1,2016-01-01,2016,1,1,04:00:00,Madrugada,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,cruce_de_calles,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4,Friday,Dia_de_Semana
1,20160002,1,2016-01-02,2016,1,2,01:15:00,Madrugada,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,cruce_de_calles,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1,Saturday,Fin_de_Semana
2,20160003,1,2016-01-03,2016,1,3,07:00:00,Mañana,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7,Sunday,Fin_de_Semana
3,20160004,1,2016-01-10,2016,1,10,00:00:00,Madrugada,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,cruce_de_calles,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0,Sunday,Fin_de_Semana
4,20160005,1,2016-01-21,2016,1,21,05:20:00,Madrugada,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,cruce_de_calles,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5,Thursday,Dia_de_Semana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,20210092,1,2021-12-12,2021,12,12,06:20:00,Madrugada,AV. RIVADAVIA Y AV. PUEYRREDON,AVENIDA,...,cruce_de_calles,3,-58.40596860,-34.61011987,PEATON-AUTO,PEATON,AUTO,6,Sunday,Fin_de_Semana
691,20210093,1,2021-12-13,2021,12,13,17:10:00,Tarde,AV. RIESTRA Y MOM,AVENIDA,...,cruce_de_calles,7,-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO,17,Monday,Dia_de_Semana
694,20210096,1,2021-12-15,2021,12,15,10:30:00,Mañana,AV. EVA PERON 4071,AVENIDA,...,4071.0,9,-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS,10,Wednesday,Dia_de_Semana
692,20210094,1,2021-12-20,2021,12,20,01:10:00,Madrugada,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,cruce_de_calles,9,-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO,1,Monday,Dia_de_Semana
693,20210095,1,2021-12-30,2021,12,30,00:43:00,Madrugada,AV. GAONA Y TERRADA,AVENIDA,...,cruce_de_calles,11,-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS,0,Thursday,Dia_de_Semana

In [33]:
homicidios_hechos.isnull().sum()

Id                   0
Cantidad_Victimas    0
Fecha                0
Anio                 0
Mes                  0
Dia                  0
Hora                 0
Franja_Horaria       0
Lugar_Hecho          0
Tipo_Calle           0
Calle                0
Altura               0
Barrio               0
Coordenada x         0
Coordenada y         0
Participantes        0
Victima              0
Acusado              0
Hora del día         0
Dia_Semana           0
Tipo_Dia             0
dtype: int64

In [34]:
homicidios_hechos.isna().sum()

Id                   0
Cantidad_Victimas    0
Fecha                0
Anio                 0
Mes                  0
Dia                  0
Hora                 0
Franja_Horaria       0
Lugar_Hecho          0
Tipo_Calle           0
Calle                0
Altura               0
Barrio               0
Coordenada x         0
Coordenada y         0
Participantes        0
Victima              0
Acusado              0
Hora del día         0
Dia_Semana           0
Tipo_Dia             0
dtype: int64

In [35]:
homicidios_hechos.head(5)

,Id,Cantidad_Victimas,Fecha,Anio,Mes,Dia,Hora,Franja_Horaria,Lugar_Hecho,Tipo_Calle,...,Altura,Barrio,Coordenada x,Coordenada y,Participantes,Victima,Acusado,Hora del día,Dia_Semana,Tipo_Dia
0,20160001,1,2016-01-01,2016,1,1,04:00:00,Madrugada,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,cruce_de_calles,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4,Friday,Dia_de_Semana
1,20160002,1,2016-01-02,2016,1,2,01:15:00,Madrugada,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,cruce_de_calles,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1,Saturday,Fin_de_Semana
2,20160003,1,2016-01-03,2016,1,3,07:00:00,Mañana,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7,Sunday,Fin_de_Semana
3,20160004,1,2016-01-10,2016,1,10,00:00:00,Madrugada,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,cruce_de_calles,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0,Sunday,Fin_de_Semana
4,20160005,1,2016-01-21,2016,1,21,05:20:00,Madrugada,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,cruce_de_calles,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5,Thursday,Dia_de_Semana

In [36]:
# Hacemos un print de los valores unicos de la columna Tipo_Calle
print(homicidios_hechos['Tipo_Calle'].unique(), "antes de realizar el cambio")

# GRAL PAZ es el nombre de una avenida, por lo que procedemos a cambiarlo por "AVENIDA"
homicidios_hechos['Tipo_Calle'] = homicidios_hechos['Tipo_Calle'].replace('GRAL PAZ', 'AVENIDA')
# hacemos un segundo print para verificar que se haya realizado el cambio
print(homicidios_hechos['Tipo_Calle'].unique(), "despues de realizar el cambio")

# Mostramos un head
homicidios_hechos.head(5)

['AVENIDA' 'GRAL PAZ' 'CALLE' 'AUTOPISTA'] antes de realizar el cambio
['AVENIDA' 'CALLE' 'AUTOPISTA'] despues de realizar el cambio

,Id,Cantidad_Victimas,Fecha,Anio,Mes,Dia,Hora,Franja_Horaria,Lugar_Hecho,Tipo_Calle,...,Altura,Barrio,Coordenada x,Coordenada y,Participantes,Victima,Acusado,Hora del día,Dia_Semana,Tipo_Dia
0,20160001,1,2016-01-01,2016,1,1,04:00:00,Madrugada,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,cruce_de_calles,8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4,Friday,Dia_de_Semana
1,20160002,1,2016-01-02,2016,1,2,01:15:00,Madrugada,AV GRAL PAZ Y AV DE LOS CORRALES,AVENIDA,...,cruce_de_calles,9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1,Saturday,Fin_de_Semana
2,20160003,1,2016-01-03,2016,1,3,07:00:00,Mañana,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7,Sunday,Fin_de_Semana
3,20160004,1,2016-01-10,2016,1,10,00:00:00,Madrugada,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,cruce_de_calles,8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0,Sunday,Fin_de_Semana
4,20160005,1,2016-01-21,2016,1,21,05:20:00,Madrugada,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,cruce_de_calles,1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5,Thursday,Dia_de_Semana

##### ya terminamos con el ETL del dataset homicidios.excel de la pagina Echos, por lo que guardare una copia del limpio.

In [37]:
homicidios_hechos.to_csv('datasets/homicidios_hechos_limpio.csv')

### Ahora empezare con el dataset Victimas 
##### (este dataset estaba en los mismos datos de homicidios, solo que en otra pagina del mismo excel)

In [38]:
homicidios_victimas = pd.read_excel('datasets/homicidios.xlsx', sheet_name='VICTIMAS')
homicidios_victimas.head(5)

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00

### Explicacion de cada columna del excel Victimas.

#### Nombres de las columnas y sus valores

| Variable                 | Descripción                                                                                           |
|--------------------------|-------------------------------------------------------------------------------------------------------|
| ID_hecho                 | Identificador único del siniestro                                                                    |
| FECHA                    | Fecha en formato dd/mm/aaaa                                                                          |
| AAAA                     | Año                                                                                                   |
| MM                       | Mes                                                                                                   |
| DD                       | Día del mes                                                                                           |
| ROL                      | Posición relativa al vehículo que presentaba la víctima en el momento del siniestro                   |
| VICTIMA                  | Vehículo que ocupaba quien haya fallecido o se haya lastimado a raíz del hecho, o bien peatón/a. Clasificación agregada del tipo de vehículos |
| SEXO                     | Sexo informado por fuente policial de la víctima                                                      |
| EDAD                     | Edad de la víctima al momento del siniestro                                                          |
| FECHA_FALLECIMIENTO      | Fecha de fallecimiento de la víctima                                                                 |

In [39]:
# lo primero va a ser el nombre de las columnas

homicidios_victimas.rename(columns={'ID_hecho':'Id',
                                    'FECHA':'Fecha',
                                    'AAAA':'Anio',
                                    'MM':'Mes',
                                    'DD':'Dia',
                                    'ROL':'Victima_Fatal',
                                    'VICTIMA':'Victima_Movilidad',
                                    'SEXO':'Sexo',
                                    'EDAD':'Edad',
                                    'FECHA_FALLECIMIENTO':'Fecha_Fallecimiento'}, inplace=True)

In [40]:
homicidios_victimas.head(5)

,Id,Fecha,Anio,Mes,Dia,Victima_Fatal,Victima_Movilidad,Sexo,Edad,Fecha_Fallecimiento
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00

In [41]:
# verificamos cantidad de nulos y tipos de datos

homicidios_victimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   717 non-null    object
 1   Fecha                717 non-null    datetime64[ns]
 2   Anio                 717 non-null    int64
 3   Mes                  717 non-null    int64
 4   Dia                  717 non-null    int64
 5   Victima_Fatal        717 non-null    object
 6   Victima_Movilidad    717 non-null    object
 7   Sexo                 717 non-null    object
 8   Edad                 717 non-null    object
 9   Fecha_Fallecimiento  717 non-null    object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB

In [42]:
homicidios_victimas.isnull().sum()

Id                     0
Fecha                  0
Anio                   0
Mes                    0
Dia                    0
Victima_Fatal          0
Victima_Movilidad      0
Sexo                   0
Edad                   0
Fecha_Fallecimiento    0
dtype: int64

### los datos se observan completos a simple vista, por lo que se procedera a la modificacion de los mismos

#### Nombres de las columnas y las modificaciones a las mismas

| Variable                 | Modificaciones                                                                                        |
|--------------------------|-------------------------------------------------------------------------------------------------------|
| Id                       | Se eliminará el elemento "-" para convertir la columna en tipo entero (integer)                                                                                                                          |
| Fecha                    | Se eliminará el horario del formato, mostrando solo la fecha                      |                                                                                                       |
| FECHA_FALLECIMIENTO      | se eliminara la colomna, ya que todas las victimas son fatales                                                             |

In [43]:
# cambio columna ID
homicidios_victimas['Id'] = homicidios_victimas['Id'].str.replace('-', '')
homicidios_victimas['Id'] = homicidios_victimas['Id'].astype(int) 

#cambios columna Fecha
homicidios_victimas['Fecha'] = homicidios_victimas['Fecha'].dt.strftime('%Y-%m-%d')

#cambios columna Fecha_Fallecimiento
homicidios_victimas = homicidios_victimas.drop(columns=["Fecha_Fallecimiento"])
homicidios_victimas

,Id,Fecha,Anio,Mes,Dia,Victima_Fatal,Victima_Movilidad,Sexo,Edad
0,20160001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19
1,20160002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70
2,20160003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30
3,20160004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18
4,20160005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29
...,...,...,...,...,...,...,...,...,...
712,20210092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50
713,20210093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18
714,20210094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43
715,20210095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27
716,20210096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60

In [44]:
# el dataset victimas ya quedo listo, por lo que pasare a guardar una copia.
homicidios_victimas.to_csv('datasets/homicidios_victimas_limpio.csv')